services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/home/ubuntu/backend
    ports:
      - "8000:8000"
      - "8888:8888"
    # env_file:
    #   - .env

  redis:
    image: redis:latest

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/node/frontend
      - /home/node/frontend/node_modules
    ports:
      - "3000:3000"